# Site
url                 : http://neofelisho.github.io
baseurl             : /neofelisho.github.io

# Dependencies
kramdown:
  input             : GFM
  syntax_highlighter: rouge

# Paginate
gems                : ["jekyll-paginate"]
paginate            : 5

# Setup
title               : Neo's メモ帳
tagline             : C#
description         : Neo's memo about programming
author:
  name              : "Neo Ho"
  email             : "neofelisho@gmail.com"
  url               : "http://neofelisho.github.io/"
  facebook_username : neofelisho
  twitter_username  : neofelisho
  github_username   : neofelisho
  